version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01
      services:
        - docker

    steps:
      - checkout
      - run:
          name: Build dev image
          command: make build-env
      - restore_cache:
          name: Restore cache
          key: cache-stable-{{ arch }}-{{ .Environment.CIRCLE_JOB }}
      - run:
          name: Build image
          command: make build
      - save_cache:
          name: Save cache
          # We use {{ epoch }} to always upload a fresh cache:
          # Of course, restore_cache will not find this exact key,
          # but it will fall back to the closest key (aka the most recent).
          # See https://discuss.circleci.com/t/add-mechanism-to-update-existing-cache-key/9014/13
          key: cache-stable-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ epoch }}
          paths:
            - "./target"
      - run:
          name: Re-tag image
          command: docker tag jarrednicholls/k8s-aws-nlb-proxy-protocol-operator $DOCKER_REPO:$CIRCLE_SHA1
      - run:
          name: Login to ECR
          command: eval $(aws ecr get-login --no-include-email --region us-east-1)
      - run:
           name: Push image to ECR
           command: docker push $DOCKER_REPO:$CIRCLE_SHA1
